spring:
  application:
    name: hf-community-hub

  datasource:
    url: jdbc:postgresql://maglev.proxy.rlwy.net:23979/railway?sslmode=require
    username: postgres
    password: gZGoYuvBhEGDGNUsrofnhnsDRGfPcSkB
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        transaction:
          jta:
            platform: null

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE