spring:
  datasource:
    url: jdbc:postgresql://mainline.proxy.rlwy.net:45251/railway?sslmode=require&ssl=true
    username: postgres
    password: vzUwvqMmSNiIAbNPQtvNaEauaqOLsEby
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000 # 30 segundos
      maximum-pool-size: 5
      idle-timeout: 30000
      max-lifetime: 1800000 # 30 minutos (requerido por Railway)
      initialization-fail-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: none # Importante para producción
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuración recomendada para Railway
  sql:
    init:
      mode: never # Desactiva inicialización automática

# Configuración de logging para diagnóstico
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: DEBUG