spring:
  application:
    name: hf-community-hub

  datasource:
    url: jdbc:postgresql://turntable.proxy.rlwy.net:44453/railway?sslmode=require
    username: postgres
    password: QFjDPSiQPOqXHbnxuWjxsxoSuDhyyyHp
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF

server:
  port: ${PORT:8080}