spring:
  application:
    name: hf-community-hub
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:mainline.proxy.rlwy.net}:${DB_PORT:45251}/${DB_NAME:railway}?sslmode=require&ssl=true
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:vzUwvqMmSNiIAbNPQtvNaEauaqOLsEby}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      max-lifetime: 1800000

server:
  port: ${PORT:8080}
  shutdown: graceful

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health