spring:
  application:
    name: hf-community-hub

  datasource:
    url: jdbc:postgresql://turntable.proxy.rlwy.net:44453/railway?sslmode=require
    username: postgres
    password: QFjDPSiQPOqXHbnxuWjxsxoSuDhyyyHp
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF

server:
  port: ${PORT:8080}