spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/railway_local
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        transaction:
          jta:
            platform: null
    open-in-view: false

  application:
    name: hf-community-hub